/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientgui;

import Util.Message;
import id.ac.itb.todolist.model.Content;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Mario
 */
class ColorTableModel extends AbstractTableModel {

    String columnNames[] = {"Nama Tugas", "Pemilik", "Kategori", "Deadline", "Assignee", "Tag", "Status"};
    Object rowData[][];  //   = {     {"Tubes 5 Progin", "raymondddddddddddddddddddddd dddddddddddddddd dddddddddddddddddddd", "Kuliah", "21 Januari 2013", "felixt, mario", "tubes, lima", Boolean.TRUE},
    //        {"Technical Report KI", "mario", "Kuliah", "21 Januari 2013", "", "makalah", Boolean.FALSE},
    //        {"Koreksi Alstruk", "felixt", "Asisten B)", "21 Januari 2013", "", "alstruk, 2011", Boolean.FALSE},
//    };
    boolean[] canEdit = new boolean[]{false, false, false, false, false, false, true};

    public ColorTableModel(int bar, int col) {
        this.rowData = new Object[bar][col];
    }
    
    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
    }

    @Override
    public int getColumnCount() {
        return columnNames.length;
    }

    @Override
    public String getColumnName(int column) {
        return columnNames[column];
    }

    @Override
    public int getRowCount() {
        return rowData.length;
    }

    @Override
    public Object getValueAt(int row, int column) {
        return rowData[row][column];
    }

    @Override
    public Class getColumnClass(int column) {
        return (getValueAt(0, column).getClass());
    }

    @Override
    public void setValueAt(Object value, int row, int column) {
        System.out.println("row " + row);
        System.out.println("column " + column);
        System.out.println("value " + value);
        rowData[row][column] = value;
    }
}

public class ClientForm extends javax.swing.JFrame {

    private String username;
    ColorTableModel tm;

    /**
     * Creates new form ClientForm
     */
    public ClientForm(String uname) throws IOException {
        username = uname;
        LoginForm.getClient().getList();
        tm = new ColorTableModel(LoginForm.getClient().getAc().size(),7);
        initTable(LoginForm.getClient().getAc());
        initComponents(uname);
    }

    public void initTable(ArrayList<Content> ac) {
        Iterator it = ac.iterator();
        int bar = 0;
        while (it.hasNext()) {
            Content temp = (Content) it.next();
            System.out.println(bar);
            tm.setValueAt(temp.getNama(), bar, 0);
            tm.setValueAt(temp.getPemilik(), bar, 1);
            tm.setValueAt(temp.getKategori(), bar, 2);
            tm.setValueAt(temp.getDeadline(), bar, 3);
            tm.setValueAt(temp.getAssignees(), bar, 4);
            tm.setValueAt(temp.getTags(), bar, 5);
            tm.setValueAt(temp.getStatus(), bar, 6);

            bar++;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//
    private void initComponents(String username) {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();


        jTable1 = new javax.swing.JTable(tm);
        jTable1.setCellSelectionEnabled(true);
        //jTable1 = new javax.swing.JTable();
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new TableCellLongTextRenderer());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new TableCellLongTextRenderer());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new TableCellLongTextRenderer());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new TableCellLongTextRenderer());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new TableCellLongTextRenderer());
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new TableCellLongTextRenderer());
        jTable1.getColumnModel().getColumn(6).setMaxWidth(50);

        jTable1.setColumnSelectionAllowed(false);
        jTable1.setRowSelectionAllowed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tubes 5 Progin : To-do-list (Daftar Tugas)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Welcome, " + username);

        jButton1.setText("Logout!");

        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                //new LoginForm().setVisible(true);
                setVisible(false);
                dispose();
            }
        });

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(41, 41, 41)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
