/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package STDLServer;

import FileHelper.FileManager;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Arief
 */
public class STDLServerGUI extends javax.swing.JFrame {

    private STDLServerController serverController;
    private boolean isOnline;
    private boolean isMultiLogin = true;;
    
    /**
     * Creates new form STDLServerGUI
     */
    public STDLServerGUI(STDLServerController sC) {
        serverController = sC;
        initComponents();
    }

    public void setConnectionStatus(boolean state){
        if(state){
            statusLabel.setText("Online");
            statusSwitchButton.setText("Switch Off");
            isOnline = true;
        } else {
            statusLabel.setText("Offline");
            statusSwitchButton.setText("Switch On");
            isOnline = false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusSwitchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        multiLabel = new javax.swing.JLabel();
        multiSwitchButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userCountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        pKey = new javax.swing.JTextField();
        xKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        openKeyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Shared To Do List Server");

        jLabel2.setText("Status :");

        statusLabel.setText("Offline");

        statusSwitchButton.setText("Switch On");
        statusSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusSwitchButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Multi Login :");

        multiLabel.setText("On");

        multiSwitchButton.setText("Switch Off");
        multiSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiSwitchButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Connection Log");

        jLabel7.setText("Current User Count :");

        userCountLabel.setText("0");

        logArea.setColumns(20);
        logArea.setRows(5);
        jScrollPane1.setViewportView(logArea);

        jLabel3.setText("Key P");

        jLabel5.setText("Key X");

        openKeyButton.setText("Open");
        openKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openKeyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userCountLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(multiLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(statusLabel)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(statusSwitchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(multiSwitchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pKey)
                                    .addComponent(xKey, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(openKeyButton)
                                .addGap(0, 15, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(statusSwitchButton)
                            .addComponent(statusLabel)
                            .addComponent(pKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multiSwitchButton)
                            .addComponent(multiLabel)
                            .addComponent(jLabel4)
                            .addComponent(xKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(userCountLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(openKeyButton)))
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusSwitchButtonActionPerformed
        // TODO add your handling code here:
        if(!isOnline){
            serverController.conStart();
        } else {
            serverController.conStop();
        }
    }//GEN-LAST:event_statusSwitchButtonActionPerformed

    private void multiSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiSwitchButtonActionPerformed
        // TODO add your handling code here:
        serverController.setMultiLogin(!isMultiLogin);
    }//GEN-LAST:event_multiSwitchButtonActionPerformed

    private void openKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openKeyButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter tFilter = new FileNameExtensionFilter(
                "ElGamal PrivateKey File (*.pri)", "pri");
        chooser.setFileFilter(tFilter);
        chooser.setDialogTitle("Open Private Key");
        int tOption = chooser.showOpenDialog(this);
        if (tOption == JFileChooser.APPROVE_OPTION) {
            String opened = FileManager.openDoc(chooser.getSelectedFile().getPath());
            String[] opened2 = opened.split("\n");
            pKey.setText(opened2[0]);
            xKey.setText(opened2[1]);
            serverController.eGG.setPublicKeyP(Integer.parseInt(opened2[0]));
            serverController.eGG.setPrivateKeyX(Integer.parseInt(opened2[1]));
        }
    }//GEN-LAST:event_openKeyButtonActionPerformed


    public void setMultiLoginStatus(boolean state){
        if(!state){
            multiLabel.setText("off");
            multiSwitchButton.setText("Switch On");
            isMultiLogin = false;
        } else {
            multiLabel.setText("on");
            multiSwitchButton.setText("Switch Off");
            isMultiLogin = true;
        }
    }
    
    public void setUserCountLabel(int label){
        userCountLabel.setText(label+"");
    }
    
    public void appendLog(String log){
        logArea.setText(logArea.getText()+log+"\n");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea logArea;
    private javax.swing.JLabel multiLabel;
    private javax.swing.JButton multiSwitchButton;
    private javax.swing.JButton openKeyButton;
    private javax.swing.JTextField pKey;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton statusSwitchButton;
    private javax.swing.JLabel userCountLabel;
    private javax.swing.JTextField xKey;
    // End of variables declaration//GEN-END:variables
}
