package SPACE;

import java.util.ArrayList;

/**
 * Class for representing participants in scheduling system in Rumah Belajar.
 * @author Jeremy Joseph Hanniel | 13510026
 */
public class Participants {
    /**
     * The ID of this participant.
     * ID is automatically generated by ordered numbering taken from corresponding file.
     */
    protected final String ID;
    /**
     * The name of this participant, be it a teacher or a student.
     */
    protected String name = null;
    /**
     * The cell phone number of this participant, be it a teacher or a student.
     * Can have more than one value.
     */
    protected String cellNo = null;
    /**
     * The subjects this participant engages in Rumah Belajar.
     * <p>
     * If it is a student; the subjects he/she applies to study.
     * On the other hand, if it is a teacher; the subjects he/she offers to teach.
     * </p>
     * <p>
     * Follows the format of ABCD where ABCD value is in binary, 1 is taken while 0 is not.
     * A = Maths, B = Physics, C = Chemistry, D = Accounting
     * </p>
     */
    protected String subjects = null;
    
    /**
     * The schedule of this student. Each cell represents a time slot of an hour from 9 to 18 each day. 0 means available, while 1 means unavailable.
     */
    protected int[][] schedule = null;
    
    /**
     * The history of lessons this student is supposed to take so far. Takes form as an arrayList whose elements are actually lessonID.
     * @see Lesson#lessonID
     */
    protected ArrayList<String> lessonHistory;
    
    /**
     * Constructor for generating a new participant.
     * @param ID the ID of the new participant
     * @param nm the name of the new participant
     * @param cell an ArrayList containing a list of the participant's cell phones number
     * @param sbj subjects the new participant engages in
     */
    public Participants (String iden, String nm, String cell, String sbj) {
        ID = iden;
        name = nm;
        cellNo = cell;
        subjects = sbj;
    }
    
    // G E T T E R   F U N C T I O N S
    
    /**
     * Gets this participant's ID.
     * @return this participant's ID
     * @see Participants#ID
     */
    public String getID() {
        return ID;
    }
    
    /**
     * Gets this participant's name.
     * @return this participant's name
     * @see Participants#name
     */
    public String getName() {
        return name;
    }
    
    /**
     * Gets this participant's list of cell phone numbers.
     * @return this participant's cell phone numbers
     * @see Participants#cellNo
     */
    public String getCellNo() {
        return cellNo;
    }
    
    /**
     * Gets this participant's subjects.
     * @return this participant's subjects.
     * @see Participants#subjects
     */
    public String getSubjects() {
        return subjects;
    }
    
    /**
     * Gets this participant's schedule.
     * @return this participant's schedule
     * @see Participants#schedule
     */
    public int[][] getSchedule() {
        return schedule;
    }
    
    /**
     * Gets this participant's lesson history.
     * @return this participant's lesson history
     */
    public ArrayList<String> getLessonHistory() {
        return lessonHistory;
    }
    
    // S E T T E R   F U N C T I O N S
    
    /**
     * Sets this participant's name.
     * @param newName the new name for this participant
     */
    public void setName (String newName) {
        name = newName;
    }
    
    /**
     * Sets this participant's cell phone numbers.
     * @param newCellNo the new ArrayList of cell phone numbers for this participant
     */
    public void setCellNo (String newCellNo) {
        cellNo = newCellNo;
    }
    
    /**
     * Sets this participant's applied subjects.
     * @param newCourses the new course set for this participant
     */
    public void setSubjects (String newCourses) {
        subjects = newCourses;
    }
    
    /**
     * Sets this participant's schedule.
     * @param newSchedule the new schedule in matrix form for this participant
     */
    public void setSchedule (int[][] newSchedule) {
        schedule = new int[7][8];
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 8; j++) {
                schedule[i][j] = newSchedule[i][j];
            }
        }
    }
    
    /**
     * Sets this participant's lesson history.
     * @param newHistory the new lesson history for this participant
     */
    public void setLessonHistory (ArrayList<String> newHistory) {
        lessonHistory = new ArrayList<>(newHistory);
    }
}
