package SPACE;

import java.util.ArrayList;

/**
 * Class for representing a lesson in Rumah Belajar.
 * @author Jeremy Joseph Hanniel | 13510026
 */
public class Lesson {
    /**
     * The unique ID for this lesson. Lesson ID is automatically generated by ordered numbering from a special file.
     */
    private final String lessonID;
    /**
     * Date and time when the lesson occurs.
     */
    private String time = null;
    /**
     * A list of subjects taught in this lesson.
     * <p>
     * Follows the format of ABCD where ABCD value is in binary, 1 is taught while 0 is not.
     * A = Maths, B = Physics, C = Chemistry, D = Accounting
     */
    private String subjects = null;
    /**
     * The teacher's ID of participating teacher in this lesson.
     * @see Participants#ID
     */
    private String teacherID;
    /**
     * The list of ID of students who participates in this lesson.
     * @see Participants#ID
     */
    private ArrayList<String> studentsID;
    
    /**
     * Constructor specifying when the lesson occurs, what subject is taught, and everyone participating in this lesson.
     * @param lessonTime when the lesson occurs
     * @param subjectTaught what subjects are taught
     * @param involvedStudentsID which students participate
     * @param involvedTeacherID which teacher is teaching
     */
    public Lesson (String ID, String lessonTime, String subjectTaught, ArrayList<String> involvedStudentsID, String involvedTeacherID) {
        lessonID = ID;
        time = lessonTime;
        subjects = subjectTaught;
        studentsID = new ArrayList<>(involvedStudentsID);
        teacherID = involvedTeacherID;
        
        // TO DO : auto-generate lesson ID
    }
    
    // G E T T E R   F U N C T I O N S
    
    public String getLessonID() {
        return lessonID;
    }
    
    public String getTime() {
        return getTime();
    }
    
    public String getSubjects() {
        return subjects;
    }
    
    public String getTeacherID() {
        return teacherID;
    }
    
    public ArrayList<String> getStudentsID() {
        return studentsID;
    }
    
    // S E T T E R   M E T H O D S
    
    public void setTime (String newTime) {
        time = newTime;
    }
    
    public void setSubjects (String newSubjects) {
        subjects = newSubjects;
    }
    
    public void setTeacherID (String newTeacherID) {
        teacherID = newTeacherID;
    }
    
    public void setStudentsID (ArrayList<String> newStudentsID) {
        studentsID = new ArrayList<>(newStudentsID);
    }
}
