/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ElGamal;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Arief
 */
public class ElGamalGUI extends javax.swing.JFrame {

    private ElGamalGenerator eGG = new ElGamalGenerator();
    private String ciphertext;
    private byte[] bytepool;
    private String stringpool;
    private int fileCode;
    
    /**
     * Creates new form ElGamalGUI
     */
    public ElGamalGUI() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pKeyPText = new javax.swing.JTextField();
        pKeyGText = new javax.swing.JTextField();
        pKeyYText = new javax.swing.JTextField();
        pKeyXText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        savePublicKeyButton = new javax.swing.JButton();
        savePrivateKeyButton = new javax.swing.JButton();
        generateKeyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ElGamalKeyGenerator");

        pKeyPText.setEditable(false);

        pKeyGText.setEditable(false);

        pKeyYText.setEditable(false);

        pKeyXText.setEditable(false);

        jLabel2.setText("Public Key P :");

        jLabel3.setText("Public Key G :");

        jLabel4.setText("Public Key Y :");

        jLabel5.setText("Private Key X :");

        savePublicKeyButton.setText("Save Public Key");
        savePublicKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePublicKeyButtonActionPerformed(evt);
            }
        });

        savePrivateKeyButton.setText("Save Private Key");
        savePrivateKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePrivateKeyButtonActionPerformed(evt);
            }
        });

        generateKeyButton.setText("Generate Key");
        generateKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateKeyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pKeyYText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pKeyXText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pKeyGText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pKeyPText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(savePublicKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savePrivateKeyButton)
                            .addComponent(generateKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pKeyPText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pKeyGText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pKeyYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pKeyXText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateKeyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savePublicKeyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savePrivateKeyButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init(){
        pKeyGText.setText("");
        pKeyPText.setText("");
        pKeyYText.setText("");
        pKeyXText.setText("");
        fileCode=1;
    }
    
    private void savePublicKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePublicKeyButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter tFilter = new FileNameExtensionFilter(
                "ElGamal PublicKey File (*.pub)", "pub");
        chooser.setFileFilter(tFilter);
        chooser.setDialogTitle("Save Public Key");
        int tOption = chooser.showSaveDialog(this);
        if (tOption == JFileChooser.APPROVE_OPTION) {
            String save = pKeyPText.getText() + "\n" + pKeyGText.getText() + "\n" + pKeyYText.getText() + "\n";
            String filepath = chooser.getSelectedFile().getPath();
            if(!filepath.endsWith(".pub"))
                filepath=filepath+".pub";
            FileHelper.saveDoc(filepath, save);
        }
    }//GEN-LAST:event_savePublicKeyButtonActionPerformed

    private void generateKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateKeyButtonActionPerformed
        // TODO add your handling code here:
        eGG.generateKey();
        pKeyGText.setText(eGG.getPublicKeyG()+"");
        pKeyPText.setText(eGG.getPublicKeyP()+"");
        pKeyXText.setText(eGG.getPrivateKeyX()+"");
        pKeyYText.setText(eGG.getPublicKeyY()+"");
    }//GEN-LAST:event_generateKeyButtonActionPerformed

    private void savePrivateKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePrivateKeyButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter tFilter = new FileNameExtensionFilter(
                "ElGamal PublicKey File (*.pri)", "pri");
        chooser.setFileFilter(tFilter);
        chooser.setDialogTitle("Save Private Key");
        int tOption = chooser.showSaveDialog(this);
        if (tOption == JFileChooser.APPROVE_OPTION) {
            String save = pKeyPText.getText() + "\n" + pKeyXText.getText() + "\n";
            String filepath = chooser.getSelectedFile().getPath();
            if(!filepath.endsWith(".pri"))
                filepath=filepath+".pri";
            FileHelper.saveDoc(filepath, save);
        }
    }//GEN-LAST:event_savePrivateKeyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElGamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElGamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElGamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElGamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ElGamalGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup fileType;
    private javax.swing.JButton generateKeyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pKeyGText;
    private javax.swing.JTextField pKeyPText;
    private javax.swing.JTextField pKeyXText;
    private javax.swing.JTextField pKeyYText;
    private javax.swing.JButton savePrivateKeyButton;
    private javax.swing.JButton savePublicKeyButton;
    // End of variables declaration//GEN-END:variables
}
